import { Button, Callout, LessonStage, RangeControl, Typography, ValueTile } from '../../shared/react';
import { RegressionPlot } from '../components/RegressionPlot';
import { mae, mse } from '../model/linearRegressionMath';
import { useLinearRegression } from '../model/LinearRegressionContext';

export function LossFunctionBlock({ onComplete }: { onComplete?: () => void }) {
  const { state, points, setPrediction, setSelectedParent, markLossChecked } = useLinearRegression(); const target = points.find((point) => point.parent === state.selectedParent) ?? points[8]; const error = target.child - state.prediction; const currentMse = mse([target], 0, state.prediction); const currentMae = mae([target], 0, state.prediction); const ready = Math.abs(error) < .6;
  return <LessonStage title="损失函数：把‘差一点’变成一个数字" description="残差保留方向；损失函数把误差变成可比较的分数。L1 看绝对距离，L2 会放大离群的大误差。">
    <div className="lr-loss-layout"><div className="lr-residual-visual"><RegressionPlot points={points} slope={.5} intercept={35} highlightParent={target.parent} /><div className="lr-number-line"><span className="lr-number-line__target" style={{ left: `${Math.max(0, Math.min(100, ((target.child - 55) / 30) * 100))}%` }} /><span className="lr-number-line__prediction" style={{ left: `${Math.max(0, Math.min(100, ((state.prediction - 55) / 30) * 100))}%` }} /></div><div className="lr-legend"><Typography variant="bodySmall" tone="danger">● 实际值 {target.child} 英寸</Typography><Typography variant="bodySmall" tone="accent">● 预测值 {state.prediction.toFixed(1)} 英寸</Typography></div><Typography variant="bodySmall" tone="muted">先选一个家庭，再把预测点拉近实际点。两点距离是 |y − ŷ|；平方后就是 (y − ŷ)²。</Typography></div><div className="lr-controls"><RangeControl label="选择父母平均身高" min={64} max={75} step={1} digits={0} value={state.selectedParent} suffix=" 英寸" onChange={(event) => setSelectedParent(Number(event.currentTarget.value))} /><RangeControl label={`父母 ${target.parent} 英寸家庭的预测`} min={55} max={85} step={.5} digits={1} value={state.prediction} suffix=" 英寸" onChange={(event) => setPrediction(Number(event.currentTarget.value))} /><div className="lr-metrics"><ValueTile label="L2 / 平方损失" value={currentMse.toFixed(2)} tone="orange" /><ValueTile label="L1 / 绝对损失" value={currentMae.toFixed(2)} tone="blue" /></div><Callout tone={ready ? 'green' : 'blue'} label="问题" text={ready ? '单个样本的损失接近 0，但整体模型仍要看全部样本。' : '把预测拉近实际值，观察 L2 下降得更快。'} /><Button variant="primary" disabled={!ready} onClick={() => { markLossChecked(); onComplete?.(); }}>用损失检查模型</Button></div></div>
  </LessonStage>;
}
