import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Button,Typography,moduleAssetUrl} from '../../../shared/react';
import {shapes,type Layer} from '../../services/digitNetworkTraining';
import {createConv3d,createPool3d,addEdges} from './legacyGeometry.js';
export function NetworkScene({layers,selected,running,stats,onSelect,onReorder,onInsert,canInsert}:{layers:Layer[];selected:number;running:boolean;stats?:number[][];onSelect:(i:number)=>void;onReorder:(from:number,to:number)=>void;onInsert:(after:number)=>void;canInsert:boolean}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({running,selected,stats,onSelect,onReorder});latest.current={running,selected,stats,onSelect,onReorder};
 const [error,setError]=useState('');const labels=useRef<(HTMLDivElement|null)[]>([]),insertion=useRef<HTMLDivElement|null>(null),previous=useRef(layers.map(l=>l.id)),pose=useRef<THREE.Vector3|null>(null);
 useEffect(()=>{const element=host.current;if(!element)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{setError('3D 画布无法初始化，仍可用下方结构按钮编辑网络。');return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(element.clientWidth,element.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;renderer.toneMappingExposure=1;element.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),root=new THREE.Group();scene.add(root);scene.add(new THREE.AmbientLight(0xffffff,2.1));const key=new THREE.DirectionalLight(0xe5efff,2.8);key.position.set(-3,5,9);scene.add(key);const rim=new THREE.DirectionalLight(0xe5efff,.25);rim.position.set(4,2,-3);scene.add(rim);
 const added=new Set(layers.filter(l=>!previous.current.includes(l.id)).map(l=>l.id));previous.current=layers.map(l=>l.id);const entries=shapes(layers),spacing=1.05,total=(layers.length+3)*spacing,camera=new THREE.PerspectiveCamera(36,element.clientWidth/element.clientHeight,.1,100);camera.position.set(-total*.08,total*.23,total*.95);if(pose.current)camera.position.copy(pose.current).multiplyScalar(total);camera.zoom=2.6*310/element.clientHeight;camera.updateProjectionMatrix();const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.enableDamping=true;orbit.minDistance=4;orbit.maxDistance=25;orbit.maxPolarAngle=Math.PI*.8;orbit.update();orbit.addEventListener('change',()=>{pose.current=camera.position.clone().divideScalar(total);});

 const pickables:THREE.Object3D[]=[],kernels:THREE.Mesh[]=[];
 function block(w:number,h:number,d:number,color:number){const mesh=new THREE.Mesh(new RoundedBoxGeometry(w,h,d,3,Math.min(.06,w/3,h/3,d/3)),new THREE.MeshStandardMaterial({color,roughness:.32,metalness:.06}));addEdges(mesh,0xffffff,.74);return mesh;}
 const input=block(.85,.85,.05,0x263037);input.position.x=-total/2+spacing/2;root.add(input);const loader=new THREE.TextureLoader();let alive=true;loader.load(moduleAssetUrl('80396753-7fc8-4f55-9188-bddbdb828169','flatten-interface/input-32.png'),texture=>{if(!alive){texture.dispose();return;}texture.colorSpace=THREE.SRGBColorSpace;const plane=new THREE.Mesh(new THREE.PlaneGeometry(.85,.85),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));plane.position.copy(input.position);plane.position.z+=.029;root.add(plane);});
 const modules:THREE.Group[]=[],targets:{x:number;y:number;z:number}[]=[];
 entries.forEach((entry,i)=>{const group=entry.layer.kind==='conv'?createConv3d(entry.layer,i,entry):createPool3d(entry.layer,i,entry);group.position.x=-total/2+(i+1.5)*spacing;
 if(entry.layer.kind==='conv'){const bounds=new THREE.Box3();group.traverse(child=>{if(child instanceof THREE.Mesh&&child.userData.role==='convKernel')bounds.expandByObject(child);});const extent=bounds.getSize(new THREE.Vector3());group.scale.set(.42/Math.max(.1,extent.x),.82/Math.max(.1,extent.y),.62/Math.max(.1,extent.z));}else{group.scale.set(1.45,1.25,1.25);group.traverse(child=>{if(child instanceof THREE.Mesh&&child.userData.role==='poolFrustum'){const geometry=child.geometry;geometry.computeBoundingBox();const extent=geometry.boundingBox!.getSize(new THREE.Vector3());group.scale.y=.85/Math.max(.1,extent.y);group.scale.z=.62/Math.max(.1,extent.z);}});}
 root.add(group);modules.push(group);targets.push({...group.scale});group.traverse(child=>{if(child instanceof THREE.Mesh&&child.userData.pickable!==false){pickables.push(child);if(child.userData.role==='convKernel')kernels.push(child);}});
 const shadow=new THREE.Mesh(new THREE.CircleGeometry(.45,40),new THREE.MeshBasicMaterial({color:0x85a8d8,transparent:true,opacity:.08,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.scale.set(1,.65,1);shadow.position.set(group.position.x,-.58,0);root.add(shadow);
 });
 const gap=new THREE.Group();gap.position.x=-total/2+(layers.length+1.5)*spacing;root.add(gap);for(let i=0;i<4;i++){const tile=block(.1,.8-i*.12,.58-i*.075,0xc7c0ed);tile.position.x=(i-1.5)*.11;gap.add(tile);}
 const halo=new THREE.Mesh(new THREE.RingGeometry(.60,.63,64),new THREE.MeshBasicMaterial({color:0x2d72db,transparent:true,opacity:.55,side:THREE.DoubleSide,depthWrite:false}));halo.position.z=-.4;root.add(halo);

 const head=new THREE.Group();head.position.x=-total/2+(layers.length+2.5)*spacing;root.add(head);const nodes:THREE.Vector3[][]=[];[4,5,3].forEach((n,layer)=>{nodes[layer]=[];for(let j=0;j<n;j++){const node=new THREE.Mesh(new THREE.SphereGeometry(.08,12,8),new THREE.MeshStandardMaterial({color:layer===1?0xffc5a8:0x9ebff1,roughness:.32}));node.position.set(layer*.24-.24,(j-(n-1)/2)*.19,0);head.add(node);nodes[layer].push(node.position.clone());}});for(let k=0;k<2;k++)for(const a of nodes[k])for(const b of nodes[k+1])head.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:0x8ba9d3,transparent:true,opacity:.55})));
 const pulse=new THREE.Mesh(new THREE.SphereGeometry(.045,12,8),new THREE.MeshBasicMaterial({color:0xf58037}));root.add(pulse);
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let startX=0,startY=0,dragIndex=-1,dragGroup:THREE.Object3D|undefined,dragOrigin=0;
 function pick(e:PointerEvent){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(pickables)[0];}
 const down=(e:PointerEvent)=>{startX=e.clientX;startY=e.clientY;const hit=pick(e);if(hit&&!latest.current.running){dragIndex=hit.object.userData.layerIndex;dragGroup=root.children.find(o=>o.userData.layerIndex===dragIndex);dragOrigin=dragGroup?.position.x??0;orbit.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);latest.current.onSelect(dragIndex);}};
 const move=(e:PointerEvent)=>{if(dragGroup&&dragIndex>=0)dragGroup.position.x=dragOrigin+(e.clientX-startX)/renderer.domElement.getBoundingClientRect().width*total;};
 const up=(e:PointerEvent)=>{if(dragGroup&&dragIndex>=0){const target=Math.max(0,Math.min(layers.length-1,Math.round((dragGroup.position.x+total/2)/spacing-1.5)));if(target!==dragIndex)latest.current.onReorder(dragIndex,target);else dragGroup.position.x=dragOrigin;}dragIndex=-1;dragGroup=undefined;orbit.enabled=true;};
 renderer.domElement.addEventListener('pointerdown',down,true);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);

 let frame=0,born=performance.now();function draw(t:number){const data=latest.current;const ease=1-Math.pow(1-Math.min(1,(t-born)/450),3);modules.forEach((g,i)=>{if(added.has(layers[i].id)){g.scale.set(targets[i].x,targets[i].y*(.35+.65*ease),targets[i].z);g.position.y=.18*(1-ease);}});halo.visible=data.selected>=0;if(halo.visible){halo.position.x=modules[data.selected]?.position.x??(-total/2+(data.selected+1.5)*spacing);halo.scale.setScalar(1+Math.sin(t/350)*.025);}pulse.visible=data.running;pulse.position.set(-total/2+(t/1800%1)*total,.32,0);kernels.forEach(mesh=>{const m=mesh.material as THREE.MeshStandardMaterial,i=mesh.userData.layerIndex,k=mesh.userData.kernelIndex,convIndex=layers.slice(0,i+1).filter(l=>l.kind==='conv').length-1;const value=data.stats?.[convIndex]?.[k];if(value!==undefined)m.color.set(value>=0?0x91b8f5:0xffc5a8);m.emissive.set(i===data.selected?0x6a99e2:0x000000);m.emissiveIntensity=i===data.selected?.12:.018;});orbit.update();for(let i=0;i<layers.length+3;i++){const label=labels.current[i];if(label){const v=new THREE.Vector3(-total/2+(i+.5)*spacing,-.86,0).project(camera);label.style.left=`${(v.x+1)/2*renderer.domElement.clientWidth}px`;label.style.top=`${(1-v.y)/2*renderer.domElement.clientHeight}px`;}}if(insertion.current){const index=data.selected<0?layers.length-1:data.selected;const v=new THREE.Vector3(-total/2+(index+2)*spacing,.75,0).project(camera);insertion.current.style.left=`${(v.x+1)/2*renderer.domElement.clientWidth}px`;insertion.current.style.top=`${(1-v.y)/2*renderer.domElement.clientHeight}px`;}renderer.render(scene,camera);frame=requestAnimationFrame(draw);}frame=requestAnimationFrame(draw);
 const resize=new ResizeObserver(()=>{renderer.setSize(element.clientWidth,element.clientHeight);camera.aspect=element.clientWidth/element.clientHeight;camera.zoom=2.6*310/element.clientHeight;camera.updateProjectionMatrix();});resize.observe(element);
 return()=>{alive=false;cancelAnimationFrame(frame);resize.disconnect();orbit.dispose();renderer.domElement.removeEventListener('pointerdown',down,true);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.Line){object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(m=>{const texture=(m as THREE.MeshBasicMaterial).map;if(texture)texture.dispose();m.dispose();});}});renderer.dispose();renderer.domElement.remove();};
 },[layers]);
 return <div className="vfl-train-stage"><div ref={host} className="vfl-train-webgl" aria-label="可旋转的3D卷积网络"/>{error&&<Typography className="vfl-train-fallback" variant="bodySmall" tone="warning">{error}</Typography>}<div className="vfl-train-object-labels">{['输入',...layers.map(l=>l.kind==='conv'?`卷积 ${l.out_channels}`:'池化'),'GAP','分类器'].map((name,i)=><div key={i} ref={el=>{labels.current[i]=el;}}>{i>0&&i<=layers.length?<Button className="vfl-train-node-label" aria-pressed={selected===i-1} onClick={()=>onSelect(i-1)} disabled={running}><Typography variant="h3" tone="accent">{name}</Typography></Button>:<Typography variant="h3" tone="accent">{name}</Typography>}</div>)}</div>{canInsert&&<div ref={insertion} className="vfl-train-insertion"><Button aria-label={selected<0?'在主干末尾插入模块':`在第 ${selected+1} 层后插入模块`} onClick={()=>onInsert(selected<0?layers.length-1:selected)}><svg width="20" height="20" viewBox="0 0 20 20" aria-hidden="true"><path d="M10 3v14M3 10h14" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg></Button></div>}</div>;
}
