import {useEffect,useMemo,useRef,useState} from 'react';
import {Button,ContentBlock,EChartsChart,MathFormulaBlock,MathFormulaStatic,RangeControl,Select,Typography} from '../../../shared/react';
import {preset,shapes,startDigitTraining,readDigitTraining,type Layer,type Job,type TrainingResult} from '../../services/digitNetworkTraining';
import {NetworkScene} from './NetworkScene';
import './NetworkTrainingPage.css';
const channels=[8,12,16,24,32,48,64];
const percent=(v?:number)=>v===undefined?'—':`${(v*100).toFixed(1)}%`;
export function NetworkTrainingPage(){
 const [layers,setLayers]=useState(preset),[selected,setSelected]=useState(-1),[kind,setKind]=useState('conv'),[channelIndex,setChannelIndex]=useState(2),[epochs,setEpochs]=useState(10),[pool,setPool]=useState('max'),[job,setJob]=useState<Job|null>(null),[result,setResult]=useState<TrainingResult|null>(null),[error,setError]=useState(''),[running,setRunning]=useState(false),[editing,setEditing]=useState(false),[notice,setNotice]=useState('');
 const abort=useRef<AbortController|null>(null);useEffect(()=>()=>abort.current?.abort(),[]);
 const entries=shapes(layers),final=entries.at(-1)?.shape??{h:28,w:28,c:1},history=job?.history??result?.history??[],last=history.at(-1);
 function change(next:Layer[]){setNotice('');setLayers(next);setJob(null);setResult(null);setError('');}
 function select(i:number){setEditing(true);setSelected(i);setKind(layers[i].kind);setPool(layers[i].pool_type);setChannelIndex(Math.max(0,channels.indexOf(layers[i].out_channels)));}
 function add(after=selected){if(layers.length>=8){setNotice('最多 8 个模块');return;}const layer:Layer={id:crypto.randomUUID(),kind:kind as Layer['kind'],out_channels:channels[channelIndex],kernel_size:kind==='pool'?2:3,stride:kind==='pool'?2:1,padding:kind==='pool'?0:1,pool_type:pool as 'max'|'avg'};const index=after<0?layers.length:after+1,next=[...layers];next.splice(index,0,layer);if(shapes(next).some(e=>e.shape.h<1||e.shape.w<1)){setNotice('这里再加池化，空间尺寸会小于 1');return;}change(next);setEditing(true);setSelected(index);setNotice(`已插入第 ${index+1} 层`);}

 function apply(){if(selected<0)return;change(layers.map((l,i)=>i===selected?{...l,kind:kind as Layer['kind'],out_channels:channels[channelIndex],pool_type:pool as 'max'|'avg',kernel_size:kind==='pool'?2:3,stride:kind==='pool'?2:1,padding:kind==='pool'?0:1}:l));}

 async function train(){abort.current?.abort();const controller=new AbortController();abort.current=controller;setError('');setJob(null);setResult(null);setRunning(true);try{let current=await startDigitTraining(layers,epochs,controller.signal);setJob(current);while(current.status==='queued'||current.status==='running'){await new Promise<void>((resolve,reject)=>{const cancel=()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));};const timer=setTimeout(()=>{controller.signal.removeEventListener('abort',cancel);resolve();},700);controller.signal.addEventListener('abort',cancel,{once:true});});current=await readDigitTraining(current.job_id,controller.signal);setJob(current);}if(current.status==='error')throw new Error(current.error||'训练失败');if(!current.result)throw new Error('训练结果为空');setResult(current.result);}catch(e){if(!controller.signal.aborted)setError(e instanceof TypeError?'训练服务未连接，请启动已有计算服务后重试。':e instanceof Error?e.message:String(e));}finally{if(!controller.signal.aborted)setRunning(false);}}
 const option=useMemo(()=>({animation:false,grid:{left:48,right:52,top:35,bottom:38},legend:{data:['损失','验证准确率'],textStyle:{fontSize:18}},tooltip:{trigger:'axis'},xAxis:{type:'category',data:history.map(e=>e.epoch),name:'轮次'},yAxis:[{type:'value',name:'损失'},{type:'value',name:'准确率',min:0,max:1,axisLabel:{formatter:(v:number)=>`${v*100}%`}}],series:[{name:'损失',type:'line',data:history.map(e=>e.loss),lineStyle:{color:'#567dae'},itemStyle:{color:'#567dae'}},{name:'验证准确率',type:'line',yAxisIndex:1,data:history.map(e=>e.val_accuracy),lineStyle:{color:'#7a9d78'},itemStyle:{color:'#7a9d78'}}]}),[history]);
 const invalid=final.h<1||final.w<1||!layers.some(l=>l.kind==='conv');
 return <ContentBlock className="vfl-train-page" headingLevel={1} title="组装并训练完整数字识别网络" subtitle="训练一次，观察卷积核和分类器怎样一起改变。"><div className={`vfl-train-body ${editing&&selected>=0?'is-editing':''} ${job||error?'has-results':''}`}>
 <div className="vfl-train-toolbar"><Select label="模块" value={kind} options={[{value:'conv',label:<Typography as="span" variant="bodySmall">卷积 + ReLU</Typography>},{value:'pool',label:<Typography as="span" variant="bodySmall">池化</Typography>}]} onChange={setKind} disabled={running}/>{kind==='conv'?<RangeControl label="输出通道" min={0} max={6} step={1} value={channelIndex} formatValue={v=>String(channels[Number(v)])} onChange={e=>setChannelIndex(Number(e.currentTarget.value))} disabled={running}/>:<Select label="池化方式" value={pool} options={[{value:'max',label:<Typography as="span" variant="bodySmall">最大池化</Typography>},{value:'avg',label:<Typography as="span" variant="bodySmall">平均池化</Typography>}]} onChange={setPool} disabled={running}/>}<div className="vfl-train-editor-actions"><Button onClick={()=>add()} disabled={running||layers.length>=8}>添加</Button><Button onClick={apply} disabled={running||selected<0}>应用到选中层</Button><Button onClick={()=>{change(layers.filter((_,i)=>i!==selected));setSelected(-1);setEditing(false);}} disabled={running||selected<0}>删除</Button></div><RangeControl label="训练轮数" min={1} max={15} value={epochs} onChange={e=>setEpochs(Number(e.currentTarget.value))} disabled={running}/><Button variant="primary" onClick={train} disabled={running||invalid}>{running?`训练中 ${job?.progress??0}%`:result?'重新训练':'训练 CNN'}</Button></div>
 <NetworkScene layers={layers} selected={selected} running={running} stats={result?.conv_stats} onInsert={i=>add(i)} canInsert={!running&&layers.length<8} onSelect={i=>{if(!running)select(i);}} onReorder={(from,to)=>{if(running)return;const next=[...layers];const item=next.splice(from,1)[0];next.splice(to,0,item);change(next);setSelected(to);}}/>
 {editing&&selected>=0&&<div className="vfl-train-editor-info"><Typography variant="bodySmall" tone={invalid?'warning':'accent'}>{invalid?'空间尺寸过小，或缺少卷积层':`第 ${selected+1} 层 · ${layers[selected].kind==='conv'?'卷积 + ReLU':'池化'}`}</Typography><MathFormulaBlock><MathFormulaStatic latex={`${entries[selected].input.h}\\times${entries[selected].input.w}\\times${entries[selected].input.c}\\;\\longrightarrow\\;${entries[selected].shape.h}\\times${entries[selected].shape.w}\\times${entries[selected].shape.c}`}/></MathFormulaBlock><Button onClick={()=>{change(preset());setSelected(-1);setEditing(false);}} disabled={running}>重置结构</Button><Button onClick={()=>{setEditing(false);setSelected(-1);}}>取消选择</Button></div>}
 {job||error?<div className="vfl-train-results"><div className="vfl-train-readout" aria-live="polite"><Typography variant="h3" tone={error?'warning':'accent'}>{error?'训练尚未开始':running?`第 ${last?.epoch??0} / ${epochs} 轮`:'训练完成'}</Typography><Typography variant="bodySmall" tone="muted">{error||job?.message}</Typography>{last&&<div className="vfl-train-metrics"><Typography variant="bodySmall" tone="accent">训练 {percent(result?.train_accuracy??last.train_accuracy)}</Typography><Typography variant="bodySmall" tone="success">验证 {percent(result?.val_accuracy??last.val_accuracy)}</Typography></div>}</div><div className="vfl-train-chart">{history.length>0&&<EChartsChart option={option} minHeight={0} style={{width:'100%',height:'100%'}} aria-label="真实训练损失和验证准确率曲线"/>}</div></div>:<Typography className="vfl-train-takeaway" variant="bodySmall" tone="muted">{notice||'点击模块选择 · 点 ＋ 插入 · 拖动模块排序'}</Typography>}
 </div></ContentBlock>;
}
