import { useEffect, useRef, useState, type CSSProperties, type PointerEvent } from 'react';
import { Button, ContentBlock, MathFormulaBlock, MathFormulaStatic, Typography, moduleAssetUrl } from '../../../shared/react';
import data from '../../../../assets/80396753-7fc8-4f55-9188-bddbdb828169/flatten-interface/responses.json';
import './FeatureMapsToClassifierPage.css';
const CHANNELS = Array.from({length:16},(_,c)=>({c,score:data.samples.reduce((sum,s)=>{const v=s.values[c],mean=v.reduce((a,b)=>a+b,0)/v.length;return sum+v.reduce((a,b)=>a+(b-mean)**2,0)/v.length;},0)})).sort((a,b)=>b.score-a.score).slice(0,5).map(item=>item.c);
const RANGES = Array.from({length:16},(_,c)=>{const v=data.samples.flatMap(s=>s.values[c]).sort((a,b)=>a-b),baseline=v[Math.floor(v.length/2)];return [baseline,Math.max(...v.map(n=>Math.abs(n-baseline)))];});
function Texture({values,size,channel}:{values:number[];size:number;channel:number}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx)return;const p=ctx.createImageData(size,size),[baseline,range]=RANGES[channel],colors=[[21,20,72],[20,65,136],[20,158,189],[112,205,108],[255,218,67]];values.forEach((v,i)=>{const t=Math.max(0,Math.min(.9999,Math.abs(v-baseline)/Math.max(range,1e-9)))*4,k=Math.floor(t),f=t-k;p.data.set([...colors[k].map((a,j)=>Math.round(a+(colors[k+1][j]-a)*f)),255],i*4);});ctx.putImageData(p,0,0);},[values,size,channel]);
  return <canvas ref={ref} width={size} height={size}/>;
}
function Formula({latex}:{latex:string}){return <MathFormulaBlock><MathFormulaStatic latex={latex}/></MathFormulaBlock>;}
export function FeatureMapsToClassifierPage(){
  const [size,setSize]=useState(32),[failed,setFailed]=useState(false);
  const scene=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;size:number;scale:number}|null>(null);
  const sample=data.samples.find(s=>s.inputSize===size)!,count=sample.values.flat().length,matched=count===784,cells=Math.round(count/49);
  function change(v:number){setSize(Math.max(28,Math.min(40,Math.round(v/4)*4)));}
  function start(e:PointerEvent<HTMLButtonElement>){e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,size,scale:(scene.current?.getBoundingClientRect().width??1540)/1540};}
  function move(e:PointerEvent<HTMLButtonElement>){const d=drag.current;if(d)change(d.size+((e.clientX-d.x)+(e.clientY-d.y))/2/d.scale/12);}
  return <ContentBlock className="vfl-flatten-page" headingLevel={1} title="从特征图到全连接分类器" subtitle="Flatten 把特征图逐行拉直、按通道拼接；全连接层接收固定长度的输入。">
    <div className="vfl-flatten-body"><div ref={scene} className={`vfl-flatten-scene ${matched?'is-matched':'is-mismatched'}`}>
      <svg className="vfl-flatten-links" viewBox="0 0 1540 500" aria-hidden="true"><defs><marker id="vfl-flat-arrow" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto"><path d="M0 0L7 4L0 8Z" fill="currentColor"/></marker></defs><path d="M290 270H345"/><path d="M637 270H720"/><path d="M1110 270H1180" className={matched?'':'vfl-flat-broken'}/></svg>
      <div className="vfl-flatten-input"><div className="vfl-flatten-input-size"><Formula latex={`${size}\\times${size}`}/></div><div className="vfl-flatten-image-zone"><div className="vfl-flatten-image" style={{width:size*7,height:size*7}}><img src={moduleAssetUrl('80396753-7fc8-4f55-9188-bddbdb828169',`flatten-interface/${sample.input}`)} alt={`数字7，${size}×${size}输入`} onError={()=>setFailed(true)}/><Button className="vfl-flatten-handle" role="slider" aria-label="拖动调整输入尺寸" aria-valuemin={28} aria-valuemax={40} aria-valuenow={size} aria-valuetext={`${size}×${size}`} onPointerDown={start} onPointerMove={move} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={e=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();change(e.key==='Home'?28:e.key==='End'?40:size+(['ArrowLeft','ArrowDown'].includes(e.key)?-4:4));}}}><span aria-hidden="true"/></Button></div></div><Typography variant="bodySmall" tone="muted">拖动右下角，缩小图像</Typography></div>
      <div className="vfl-flatten-maps"><Typography variant="bodySmall" tone="accent">卷积后的特征图</Typography><div className="vfl-flatten-stack" style={{'--map-side':`${sample.mapSize*18}px`} as CSSProperties}>{[...CHANNELS].reverse().map((channel,i)=><div key={channel} className="vfl-flatten-plane" style={{'--depth':4-i} as CSSProperties}><Texture values={sample.values[channel]} size={sample.mapSize} channel={channel}/></div>)}</div><Formula latex={`${sample.mapSize}\\times${sample.mapSize}\\times16`}/><Typography variant="bodySmall" tone="muted">16 个通道，示出 5 个</Typography></div>
      <div className="vfl-flatten-vector"><Typography variant="h3" tone="accent">Flatten：拉直</Typography><div className="vfl-flatten-unroll"><svg viewBox="0 0 330 70" aria-hidden="true"><path d="M5 10H75V25H5V40H75V55H5M95 32H325M312 24L325 32L312 40"/></svg><Typography variant="bodySmall" tone="muted">逐行展开，逐通道拼接</Typography></div><div className="vfl-flatten-vector-length"><Formula latex={`${count}`}/><Typography variant="bodySmall" tone="muted">个数</Typography></div><div className="vfl-flatten-cubes" style={{'--cube-count':cells} as CSSProperties} aria-label={`展平向量共${count}个数，每个方块示意一段数值`}>{Array.from({length:cells},(_,i)=><span key={i} className={i>=16?'is-extra':''}/>)}</div><Typography variant="bodySmall" tone="muted">数值不变，只改变排列</Typography></div>
      <div className="vfl-flatten-classifier"><div className="vfl-flatten-fixed"><Typography variant="h3" tone="accent">全连接层输入固定</Typography><Formula latex="784"/></div><div className="vfl-flatten-network"><div className="vfl-flatten-port"><Formula latex="784"/></div><svg viewBox="0 0 300 260" aria-label="固定接收784个数的全连接网络，节点仅示意"><g className="vfl-flatten-wires">{[65,105,145,205].flatMap(a=>[45,100,155,220].map(b=><line key={`${a}-${b}`} x1="45" y1={a} x2="145" y2={b}/>))}{[45,100,155,220].flatMap(a=>[85,140,195].map(b=><line key={`${a}-${b}`} x1="145" y1={a} x2="248" y2={b}/>))}</g><rect className="vfl-flatten-socket" x="23" y="43" width="44" height="182" rx="6"/>{[65,105,145,205].map(y=><circle key={`i${y}`} cx="45" cy={y} r="10"/>)}{[45,100,155,220].map(y=><circle key={`h${y}`} cx="145" cy={y} r="13"/>)}{[85,140,195].map(y=><circle key={`o${y}`} cx="248" cy={y} r="12"/>)}<path className="vfl-flatten-ellipsis" d="M45 165v2m0 10v2m0 10v2M280 130v2m0 10v2m0 10v2"/></svg><div className="vfl-flatten-fit"><Formula latex={`${count}${matched?'=':'\\ne'}784`}/></div></div></div>
    </div><div className={`vfl-flatten-cause ${matched?'is-matched':''}`} aria-live="polite"><Typography variant="h3" tone="accent">输入尺寸改变</Typography><span aria-hidden="true">→</span><Typography variant="h3" tone="accent">展平长度改变</Typography><span aria-hidden="true">→</span><Typography variant="h3" tone={matched?'success':'warning'}>{matched?'长度匹配，可以接入':'原来的全连接层无法接收'}</Typography></div><div className="vfl-flatten-caption"><Typography variant="bodySmall" tone="muted">卷积核不绑定固定的输入宽高；固定全连接层要求输入元素数量一致。</Typography><Button onClick={()=>change(32)}>恢复初始尺寸</Button></div><Typography className="vfl-flatten-source" variant="bodySmall" tone={failed?'danger':'muted'}>{failed?'图像加载失败，请刷新重试。':'真实特征响应；颜色表示偏离通道基线的强度。向量方块与网络节点为示意。'}</Typography></div>
  </ContentBlock>;
}
