(function (global) {
  'use strict';

  var game = global.Act3DisguiseGame = global.Act3DisguiseGame || {};

  var SCENE_WIDTH = 1448;
  var SCENE_HEIGHT = 1086;
  var ASSET_ROOT = './game_assets/';
  var EMBEDDING_SIMILARITY_URL = 'http://127.0.0.1:59415/face-recog/embedding-similarity';
  var OVERLAY_ASSET = 'overlay_layer.png';
  var PLAYER_ACTOR = 'balujun';
  var PLAYER_SPEED = 260;
  var OVERLAY_COLLISION_TILE = 16;
  var OVERLAY_ALPHA_THRESHOLD = 32;
  var OVERLAY_SOLID_COVERAGE = 0.12;
  var OVERLAY_DEPTH = 10;
  var NAV_COLLISION_PADDING = 12;
  var ACTOR_DEPTH_BASE = 100;
  var ACTOR_DISPLAY_HEIGHT = 164;
  var ACTOR_DIRECTIONS = ['down', 'left', 'right', 'up'];
  var VIGNETTE_DEPTH = 200;
  var UI_DEPTH = 10000;
  var TRIGGER_DEPTH = 500;
  var FACE_SAMPLE_WIDTH = 256;
  var FACE_SAMPLE_HEIGHT = 256;
  var EDIT_IMAGE_BOX = 360;
  var DISGUISE_PASS_THRESHOLD = 50;
  var DRESSER_TRIGGER = { x: 278, y: 408, radius: 86 };
  var DISGUISE_ICON_ROOT = 'logo_svg/';

  game.constants = {
    SCENE_WIDTH: SCENE_WIDTH,
    SCENE_HEIGHT: SCENE_HEIGHT,
    ASSET_ROOT: ASSET_ROOT,
    EMBEDDING_SIMILARITY_URL: EMBEDDING_SIMILARITY_URL,
    OVERLAY_ASSET: OVERLAY_ASSET,
    PLAYER_ACTOR: PLAYER_ACTOR,
    PLAYER_SPEED: PLAYER_SPEED,
    OVERLAY_COLLISION_TILE: OVERLAY_COLLISION_TILE,
    OVERLAY_ALPHA_THRESHOLD: OVERLAY_ALPHA_THRESHOLD,
    OVERLAY_SOLID_COVERAGE: OVERLAY_SOLID_COVERAGE,
    OVERLAY_DEPTH: OVERLAY_DEPTH,
    NAV_COLLISION_PADDING: NAV_COLLISION_PADDING,
    ACTOR_DEPTH_BASE: ACTOR_DEPTH_BASE,
    ACTOR_DISPLAY_HEIGHT: ACTOR_DISPLAY_HEIGHT,
    ACTOR_DIRECTIONS: ACTOR_DIRECTIONS,
    VIGNETTE_DEPTH: VIGNETTE_DEPTH,
    UI_DEPTH: UI_DEPTH,
    TRIGGER_DEPTH: TRIGGER_DEPTH,
    FACE_SAMPLE_WIDTH: FACE_SAMPLE_WIDTH,
    FACE_SAMPLE_HEIGHT: FACE_SAMPLE_HEIGHT,
    EDIT_IMAGE_BOX: EDIT_IMAGE_BOX,
    DISGUISE_PASS_THRESHOLD: DISGUISE_PASS_THRESHOLD,
    DRESSER_TRIGGER: DRESSER_TRIGGER,
    DISGUISE_ICON_ROOT: DISGUISE_ICON_ROOT
  };
}(window));
